OpafProjectVisualForcePages/force-app/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <label>Facility</label>
</RecordType>

OpafProjectVfMods/force-app/main/default/objects/Account/recordTypes/Provider.recordType-meta.xml
<RecordType>
    <fullName>Provider</fullName>
    <active>true</active>
    <label>Provider</label>
</RecordType>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/Enrollment_Status__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Status__c</fullName>
    <label>Enrollment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Missing Information</fullName>
            </value>
            <value>
                <fullName>Denied by Mail</fullName>
            </value>
            <value>
                <fullName>Denied by Phone</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pre-Qualified</fullName>
            </value>
            <value>
                <fullName>Saved to Complete Later</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Case/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Facilitys</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Case/fields/Prescriber__c.field-meta.xml
<CustomField>
    <fullName>Prescriber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prescriber</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Provider)</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Case/fields/Prescription1__c.field-meta.xml
<CustomField>
    <fullName>Prescription1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prescription</label>
    <referenceTo>Prescription__c</referenceTo>
    <relationshipLabel>Cases (Prescription)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Case/fields/Prescription__c.field-meta.xml
<CustomField>
    <fullName>Prescription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prescription</label>
    <referenceTo>HealthCloudGA__EhrMedicationPrescription__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABILIFY_ASIMTUFII</fullName>
                <label>ABILIFY ASIMTUFII</label>
            </value>
            <value>
                <fullName>ABILIFY_MAINTENA</fullName>
                <label>ABILIFY MAINTENA</label>
            </value>
            <value>
                <fullName>JYNARQUE</fullName>
            </value>
            <value>
                <fullName>REXULTI</fullName>
            </value>
            <value>
                <fullName>SAMSCA</fullName>
            </value>
            <value>
                <fullName>NUEDEXTA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Prescriber</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <inlineHelpText>Custom Gender field non HC</inlineHelpText>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Contact/fields/HealthCloudGA__Gender__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Decline to Specify</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Contact/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <label>SSN</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Contact/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Contact/recordTypes/Provider.recordType-meta.xml
<RecordType>
    <fullName>Provider</fullName>
    <active>true</active>
    <label>Provider</label>
</RecordType>

OpafProjectVfMods/force-app/main/default/objects/Prescription__c/Prescription__c.object-meta.xml
<CustomObject>
    <label>Prescription</label>
    <nameField>
        <label>Prescription  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prescriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OpafProjectVfMods/force-app/main/default/objects/Prescription__c/fields/Dosage__c.field-meta.xml
<CustomField>
    <fullName>Dosage__c</fullName>
    <label>Dosage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>300 mg</fullName>
            </value>
            <value>
                <fullName>400 mg</fullName>
            </value>
            <value>
                <fullName>30 &amp; 15 mg</fullName>
            </value>
            <value>
                <fullName>45 &amp; 15 mg</fullName>
            </value>
            <value>
                <fullName>60 &amp; 30 mg</fullName>
            </value>
            <value>
                <fullName>90 &amp; 30 mg</fullName>
            </value>
            <value>
                <fullName>15 mg</fullName>
            </value>
            <value>
                <fullName>0.25 mg</fullName>
            </value>
            <value>
                <fullName>0.5 mg</fullName>
            </value>
            <value>
                <fullName>1 mg</fullName>
            </value>
            <value>
                <fullName>2 mg</fullName>
            </value>
            <value>
                <fullName>3 mg</fullName>
            </value>
            <value>
                <fullName>4 mg</fullName>
            </value>
            <value>
                <fullName>30 mg</fullName>
            </value>
            <value>
                <fullName>720 mg</fullName>
            </value>
            <value>
                <fullName>960 mg</fullName>
            </value>
            <value>
                <fullName>PO QDx7/PO Q12H</fullName>
            </value>
            <value>
                <fullName>PO Q12H</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Prescription__c/fields/Number_of_Refills__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Refills__c</fullName>
    <label>Number of Refills</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Prescription__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Formula field from Case record</description>
    <formula>Text(Case__r.Product__c)</formula>
    <inlineHelpText>Formula field from Case record</inlineHelpText>
    <label>Product</label>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Prescription__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/classes/OPAF_NeuroscienceEnrollmentComponentTest.cls
@isTest
public with sharing class OPAF_NeuroscienceEnrollmentComponentTest {
	@testSetup
    public static void commonSetup() { 
        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Facility').getRecordTypeId();
        Id PatientRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        Id PrescriberRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Provider').getRecordTypeId();
        Account accountRecord = new Account(Name = 'Test Account',
                                 	RecordTypeId = RecordTypeIdAccount
                                 	);
        insert accountRecord;
        
        Contact patientRecord = new Contact(FirstName = 'Test',
                                            LastName = 'Patient',
                                            RecordTypeId = PatientRecordTypeId,
                                           	Email = 'test@test.com',
                                           	Birthdate = system.today().addYears(-20),
                                           	SSN__c = '123456789',
                                           	HomePhone = '12345678890',
                                           	HealthCloudGA__Gender__c = 'Male',
                                           	Gender__c = 'Male',
                                           	Street_Address__c = 'Test Street',
                                           	Address_Line_2__c = 'Test',
                                           	City__c = 'Tulsa',
                                           	State__c = 'OK',
                                           	Zip_Code__c = '12345');
        insert patientRecord;
        
        Contact prescriberRecord = new Contact(FirstName = 'Test',
                                 	LastName = 'Prescriber',
                                 	RecordTypeId = PrescriberRecordTypeId);
        insert prescriberRecord;
        
        Prescription__c prescriptionRecord = new Prescription__c(Name = 'Test Prescription',
                                                                	Quantity__c = '4',
                                                                	Number_of_Refills__c = '4',
                                                                	Dosage__c = '300 mg');
        insert prescriptionRecord;
        
        Case caseRecord = new Case(Patient__c = patientRecord.Id,
                                  	Facility__c = accountRecord.Id,
                                  	Prescriber__c = prescriberRecord.Id,
                                  	Prescription1__c = prescriptionRecord.Id,
                                  	Enrollment_Status__c = 'Saved to Complete Later',
                                  	Product__c = 'ABILIFY MAINTENA',
                                  	User_Type__c = 'Prescriber');
        insert caseRecord;
        
        ContentVersion contentVersionRecord = new ContentVersion(Title = 'Test Doc',
                                                                	PathOnClient='/Test Doc.pdf',
                                                                	VersionData = blob.valueOf('Test'),
                                                                	origin = 'H',
                                                                	FirstPublishLocationId = caseRecord.Id,
                                                                	Document_Type__c = 'INSURANCE DOCUMENT');
        insert contentVersionRecord;
    } 
    
    testmethod static void testIfMethods(){
        Case cs = [SELECT Id FROM Case LIMIT 1];
        Test.startTest();
    	OPAF_NeuroscienceEnrollmentVfComponent NEF = new OPAF_NeuroscienceEnrollmentVfComponent();
        NEF.setCaseRecId(cs.Id);
        NEF.getCaseRecId();
        NEF.CaserecordDate();
        Test.stopTest();
    }
}