OpafProjectVfMods/force-app/main/default/objects/Case/fields/Enrollment_Status__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Status__c</fullName>
    <label>Enrollment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Missing Information</fullName>
            </value>
            <value>
                <fullName>Denied by Mail</fullName>
            </value>
            <value>
                <fullName>Denied by Phone</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pre-Qualified</fullName>
            </value>
            <value>
                <fullName>Saved to Complete Later</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Case/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Facilitys</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABILIFY_ASIMTUFII</fullName>
                <label>ABILIFY ASIMTUFII</label>
            </value>
            <value>
                <fullName>ABILIFY_MAINTENA</fullName>
                <label>ABILIFY MAINTENA</label>
            </value>
            <value>
                <fullName>JYNARQUE</fullName>
            </value>
            <value>
                <fullName>REXULTI</fullName>
            </value>
            <value>
                <fullName>SAMSCA</fullName>
            </value>
            <value>
                <fullName>NUEDEXTA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Prescriber</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Consent__c/Consent__c.object-meta.xml
<CustomObject>
    <label>Consent</label>
    <nameField>
        <displayFormat>CON-{000000}</displayFormat>
        <label>Consent</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OpafProjectVfMods/force-app/main/default/objects/Consent__c/fields/Consent_Type__c.field-meta.xml
<CustomField>
    <fullName>Consent_Type__c</fullName>
    <label>Consent Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Consent</fullName>
            </value>
            <value>
                <fullName>Re-Enrollment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Consent__c/fields/Contact_Record__c.field-meta.xml
<CustomField>
    <fullName>Contact_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Record</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consent</relationshipLabel>
    <relationshipName>Consent</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Consent__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consent (Patient)</relationshipLabel>
    <relationshipName>Consent1</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Consent__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <inlineHelpText>Select the product that you are submitting your application for</inlineHelpText>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABILIFY MAINTENA</fullName>
            </value>
            <value>
                <fullName>JYNARQUE</fullName>
            </value>
            <value>
                <fullName>REXULTI</fullName>
            </value>
            <value>
                <fullName>SAMSCA</fullName>
            </value>
            <value>
                <fullName>ABILIFY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <inlineHelpText>Custom Gender field non HC</inlineHelpText>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Contact/fields/HealthCloudGA__Gender__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Decline to Specify</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Contact/fields/Legal_Rep_Condition_Check__c.field-meta.xml
<CustomField>
    <fullName>Legal_Rep_Condition_Check__c</fullName>
    <label>Legal Rep Condition Check</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>true</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Contact/fields/Legal_Rep_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Rep_First_Name__c</fullName>
    <label>Legal Rep First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Contact/fields/Legal_Rep_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Rep_Last_Name__c</fullName>
    <label>Legal Rep Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Contact/fields/Legal_Rep_Phone__c.field-meta.xml
<CustomField>
    <fullName>Legal_Rep_Phone__c</fullName>
    <label>Legal Rep Phone</label>
    <type>Phone</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Contact/fields/Legal_Rep_Rel_Other__c.field-meta.xml
<CustomField>
    <fullName>Legal_Rep_Rel_Other__c</fullName>
    <label>Legal Rep Rel Other</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Contact/fields/Legal_RepRelTypec__c.field-meta.xml
<CustomField>
    <fullName>Legal_RepRelTypec__c</fullName>
    <label>Legal Rep_Rel_Type__c</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Adult Child</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Adult Sibling</fullName>
            </value>
            <value>
                <fullName>Other (please specify)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Contact/fields/Medical_Assistant_Name__c.field-meta.xml
<CustomField>
    <fullName>Medical_Assistant_Name__c</fullName>
    <label>Medical Assistant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Contact/fields/Medical_Assistant_Phone__c.field-meta.xml
<CustomField>
    <fullName>Medical_Assistant_Phone__c</fullName>
    <label>Medical Assistant Phone</label>
    <type>Phone</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Contact/fields/Phone_Extension__c.field-meta.xml
<CustomField>
    <fullName>Phone_Extension__c</fullName>
    <label>Phone Extension</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Contact/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Contact/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <label>SSN</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Contact/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/classes/DS_OPAFControllerTest.cls
@isTest
private class DS_OPAFControllerTest {
    @isTest
    static void service_call() {
         Account ac = new Account(name ='Grazitti') ;
        insert ac;
        
        Id contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        Contact con = new Contact(LastName ='testCon',FirstName='test',Email='test@gmail.com',recordtypeId=contactRecordTypeId,Street_Address__c='test',Address_Line_2__c='test',City__c='test',phone='343434343',Birthdate=system.today().addDays(-10),State__c='Az',SSN__c='454',Phone_Extension__c='455',Salutation__c='mr',HomePhone='343454545454',HealthCloudGA__Gender__c='female',Gender__c='female',Zip_Code__c='89898',Legal_Rep_Condition_Check__c='true',AccountId = ac.Id);
        insert con;
        contact con1 = [SELECT Id,lastname,firstname,Email,Birthdate,Legal_Rep_First_Name__c,Street_Address__c,Medical_Assistant_Name__c,Fax,Medical_Assistant_Phone__c,Phone_Extension__c,Salutation__c,Legal_Rep_Last_Name__c,Legal_Rep_Phone__c,Legal_Rep_Condition_Check__c,State__c,SSN__c,Zip_Code__c,phone,HomePhone,HealthCloudGA__Gender__c,Gender__c,Legal_RepRelTypec__c,Legal_Rep_Rel_Other__c,Address_Line_2__c,City__c FROM contact WHERE LastName='testCon' LIMIT 1];
         Consent__c consent = new Consent__c(Contact_Record__c=con.id,Consent_Type__c='New Consent');
         insert consent;
        try {
            test.startTest(); 
            Test.setMock(HttpCalloutMock.class, new RestMock());
            string a=DS_OPAFController.sendPatientConsent(con1.id,'Patient');
            test.stopTest();
        }
        catch (Exception e) {
                system.assert(e.getMessage() != null);
         }
           
    }   
    
    @isTest
    static void service_callSign() {
         Account ac = new Account(name ='Grazitti') ;
        insert ac;
        
        Id contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        Contact con = new Contact(LastName ='testCon',FirstName='test',Email='test@gmail.com',recordtypeId=contactRecordTypeId,Street_Address__c='test',Address_Line_2__c='test',City__c='test',phone='343434343',Birthdate=system.today().addDays(-10),State__c='Az',SSN__c='454',Phone_Extension__c='455',Salutation__c='mr',HomePhone='343454545454',HealthCloudGA__Gender__c='female',Gender__c='female',Zip_Code__c='89898',Legal_Rep_Condition_Check__c='true',AccountId = ac.Id);
        insert con;
        contact con1 = [SELECT Id,lastname,firstname,Email,Birthdate,Legal_Rep_First_Name__c,Street_Address__c,Medical_Assistant_Name__c,Fax,Medical_Assistant_Phone__c,Phone_Extension__c,Salutation__c,Legal_Rep_Last_Name__c,Legal_Rep_Phone__c,Legal_Rep_Condition_Check__c,State__c,SSN__c,Zip_Code__c,phone,HomePhone,HealthCloudGA__Gender__c,Gender__c,Legal_RepRelTypec__c,Legal_Rep_Rel_Other__c,Address_Line_2__c,City__c FROM contact WHERE LastName='testCon' LIMIT 1];
         Consent__c consent = new Consent__c(Contact_Record__c=con.id,Consent_Type__c='New Consent');
         insert consent;
        try {
            test.startTest(); 
                Test.setMock(HttpCalloutMock.class, new RestMock());
                DS_OPAFController ds = new DS_OPAFController();
                string Signer = DS_OPAFController.embedded_signing(new DocuSignTK.APIServiceSoap(), 'b1ab9d97-6bf0-4f5d-be2f-b6bc7a4d1be0', '', 'Testing', 'Testing@gmail.com', con.Id, consent.id);
            test.stopTest();
        }
        catch (Exception e) {
                system.assert(e.getMessage() != null);
         }
           
    }
    
    @isTest
    static void secondSigner() {
         Account ac = new Account(name ='Grazitti') ;
        insert ac;
        
        Id contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        Contact con = new Contact(LastName ='testCon',FirstName='test',Email='test@gmail.com',recordtypeId=contactRecordTypeId,Street_Address__c='test',Address_Line_2__c='test',City__c='test',phone='343434343',Birthdate=system.today().addDays(-10),State__c='Az',SSN__c='454',Phone_Extension__c='455',Salutation__c='mr',HomePhone='343454545454',HealthCloudGA__Gender__c='female',Gender__c='female',Zip_Code__c='89898',Legal_Rep_Condition_Check__c='true',AccountId = ac.Id);
        insert con;
        contact con1 = [SELECT Id,lastname,firstname,Email,Birthdate,Legal_Rep_First_Name__c,Street_Address__c,Medical_Assistant_Name__c,Fax,Medical_Assistant_Phone__c,Phone_Extension__c,Salutation__c,Legal_Rep_Last_Name__c,Legal_Rep_Phone__c,Legal_Rep_Condition_Check__c,State__c,SSN__c,Zip_Code__c,phone,HomePhone,HealthCloudGA__Gender__c,Gender__c,Legal_RepRelTypec__c,Legal_Rep_Rel_Other__c,Address_Line_2__c,City__c FROM contact WHERE LastName='testCon' LIMIT 1];
         Consent__c consent = new Consent__c(Contact_Record__c=con.id,Consent_Type__c='New Consent');
         insert consent;
        try {
            test.startTest(); 
                Test.setMock(HttpCalloutMock.class, new RestMock());
                DS_OPAFController ds = new DS_OPAFController();
                string Signer = DS_OPAFController.secondSigner('b1ab9d97-6bf0-4f5d-be2f-b6bc7a4d1be0', '', 'Testing', 'Testing@gmail.com', con.Id, 'ReEnrollmentApp');
            test.stopTest();
        }
        catch (Exception e) {
                system.assert(e.getMessage() != null);
         }
           
    }
    
    @isTest
    static void sendPrescriberConsent() {
         Account ac = new Account(name ='Grazitti') ;
        insert ac;
        
        Id contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        Contact con = new Contact(LastName ='testCon',FirstName='test',Email='test@gmail.com',recordtypeId=contactRecordTypeId,Street_Address__c='test',Address_Line_2__c='test',City__c='test',phone='343434343',Birthdate=system.today().addDays(-10),State__c='Az',SSN__c='454',Phone_Extension__c='455',Salutation__c='mr',HomePhone='343454545454',HealthCloudGA__Gender__c='female',Gender__c='female',Zip_Code__c='89898',Legal_Rep_Condition_Check__c='true',AccountId = ac.Id);
        insert con;
        contact con1 = [SELECT Id,lastname,firstname,Email,Birthdate,Legal_Rep_First_Name__c,Street_Address__c,Medical_Assistant_Name__c,Fax,Medical_Assistant_Phone__c,Phone_Extension__c,Salutation__c,Legal_Rep_Last_Name__c,Legal_Rep_Phone__c,Legal_Rep_Condition_Check__c,State__c,SSN__c,Zip_Code__c,phone,HomePhone,HealthCloudGA__Gender__c,Gender__c,Legal_RepRelTypec__c,Legal_Rep_Rel_Other__c,Address_Line_2__c,City__c FROM contact WHERE LastName='testCon' LIMIT 1];
         Consent__c consent = new Consent__c(Contact_Record__c=con.id,Consent_Type__c='New Consent');
         insert consent;
        Case caseRecord = new Case(Patient__c = con.Id,
                                  	Facility__c = ac.Id,
                                  	Enrollment_Status__c = 'Saved to Complete Later',
                                  	Product__c = 'ABILIFY MAINTENA',
                                  	User_Type__c = 'Prescriber');
        insert caseRecord;
        try {
            test.startTest(); 
                Test.setMock(HttpCalloutMock.class, new RestMock());
                DS_OPAFController ds = new DS_OPAFController();
                string Signer = DS_OPAFController.sendPrescriberConsent(caseRecord.Id, 'ReEnrollmentApp');
            test.stopTest();
        }
        catch (Exception e) {
                system.assert(e.getMessage() != null);
         }
           
    }
    
    @isTest
    static void getSignedDocument() {
         Account ac = new Account(name ='Grazitti') ;
        insert ac;
        
        Id contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        Contact con = new Contact(LastName ='testCon',FirstName='test',Email='test@gmail.com',recordtypeId=contactRecordTypeId,Street_Address__c='test',Address_Line_2__c='test',City__c='test',phone='343434343',Birthdate=system.today().addDays(-10),State__c='Az',SSN__c='454',Phone_Extension__c='455',Salutation__c='mr',HomePhone='343454545454',HealthCloudGA__Gender__c='female',Gender__c='female',Zip_Code__c='89898',Legal_Rep_Condition_Check__c='true',AccountId = ac.Id);
        insert con;
        contact con1 = [SELECT Id,lastname,firstname,Email,Birthdate,Legal_Rep_First_Name__c,Street_Address__c,Medical_Assistant_Name__c,Fax,Medical_Assistant_Phone__c,Phone_Extension__c,Salutation__c,Legal_Rep_Last_Name__c,Legal_Rep_Phone__c,Legal_Rep_Condition_Check__c,State__c,SSN__c,Zip_Code__c,phone,HomePhone,HealthCloudGA__Gender__c,Gender__c,Legal_RepRelTypec__c,Legal_Rep_Rel_Other__c,Address_Line_2__c,City__c FROM contact WHERE LastName='testCon' LIMIT 1];
         Consent__c consent = new Consent__c(Contact_Record__c=con.id,Consent_Type__c='New Consent');
         insert consent;
        try {
            test.startTest(); 
                Test.setMock(HttpCalloutMock.class, new RestMock());
                DS_OPAFController ds = new DS_OPAFController();
                string Signer = DS_OPAFController.getSignedDocument('b1ab9d97-6bf0-4f5d-be2f-b6bc7a4d1be0');
            test.stopTest();
        }
        catch (Exception e) {
                system.assert(e.getMessage() != null);
         }
           
    }
    
    @isTest
    static void getCertDocument() {
         Account ac = new Account(name ='Grazitti') ;
        insert ac;
        
        Id contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        Contact con = new Contact(LastName ='testCon',FirstName='test',Email='test@gmail.com',recordtypeId=contactRecordTypeId,Street_Address__c='test',Address_Line_2__c='test',City__c='test',phone='343434343',Birthdate=system.today().addDays(-10),State__c='Az',SSN__c='454',Phone_Extension__c='455',Salutation__c='mr',HomePhone='343454545454',HealthCloudGA__Gender__c='female',Gender__c='female',Zip_Code__c='89898',Legal_Rep_Condition_Check__c='true',AccountId = ac.Id);
        insert con;
        contact con1 = [SELECT Id,lastname,firstname,Email,Birthdate,Legal_Rep_First_Name__c,Street_Address__c,Medical_Assistant_Name__c,Fax,Medical_Assistant_Phone__c,Phone_Extension__c,Salutation__c,Legal_Rep_Last_Name__c,Legal_Rep_Phone__c,Legal_Rep_Condition_Check__c,State__c,SSN__c,Zip_Code__c,phone,HomePhone,HealthCloudGA__Gender__c,Gender__c,Legal_RepRelTypec__c,Legal_Rep_Rel_Other__c,Address_Line_2__c,City__c FROM contact WHERE LastName='testCon' LIMIT 1];
         Consent__c consent = new Consent__c(Contact_Record__c=con.id,Consent_Type__c='New Consent');
         insert consent;
        try {
            test.startTest(); 
                Test.setMock(HttpCalloutMock.class, new RestMock());
                DS_OPAFController ds = new DS_OPAFController();
                DS_OPAFController.getCertDocument('b1ab9d97-6bf0-4f5d-be2f-b6bc7a4d1be0');
            test.stopTest();
        }
        catch (Exception e) {
                system.assert(e.getMessage() != null);
         }
           
    }
    
    @isTest
    static void sendPatientEmbededSigningURL() {
         Account ac = new Account(name ='Grazitti') ;
        insert ac;
        
        Id contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        Contact con = new Contact(LastName ='testCon',FirstName='test',Email='test@gmail.com',recordtypeId=contactRecordTypeId,Street_Address__c='test',Address_Line_2__c='test',City__c='test',phone='343434343',Birthdate=system.today().addDays(-10),State__c='Az',SSN__c='454',Phone_Extension__c='455',Salutation__c='mr',HomePhone='343454545454',HealthCloudGA__Gender__c='female',Gender__c='female',Zip_Code__c='89898',Legal_Rep_Condition_Check__c='true',AccountId = ac.Id);
        insert con;
        contact con1 = [SELECT Id,lastname,firstname,Email,Birthdate,Legal_Rep_First_Name__c,Street_Address__c,Medical_Assistant_Name__c,Fax,Medical_Assistant_Phone__c,Phone_Extension__c,Salutation__c,Legal_Rep_Last_Name__c,Legal_Rep_Phone__c,Legal_Rep_Condition_Check__c,State__c,SSN__c,Zip_Code__c,phone,HomePhone,HealthCloudGA__Gender__c,Gender__c,Legal_RepRelTypec__c,Legal_Rep_Rel_Other__c,Address_Line_2__c,City__c FROM contact WHERE LastName='testCon' LIMIT 1];
         Consent__c consent = new Consent__c(Contact_Record__c=con.id,Consent_Type__c='New Consent');
         insert consent;
        try {
            test.startTest(); 
                Test.setMock(HttpCalloutMock.class, new RestMock());
                DS_OPAFController ds = new DS_OPAFController();
                DS_OPAFController.EnvelopeSendResponse Signer = DS_OPAFController.sendPatientEmbededSigningURL(con.Id, '');
            test.stopTest();
        }
        catch (Exception e) {
                system.assert(e.getMessage() != null);
         }
           
    }
    
    @isTest
    static void getEmbeddedSigningUrl() {
         Account ac = new Account(name ='Grazitti') ;
        insert ac;
        
        Id contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        Contact con = new Contact(LastName ='testCon',FirstName='test',Email='test@gmail.com',recordtypeId=contactRecordTypeId,Street_Address__c='test',Address_Line_2__c='test',City__c='test',phone='343434343',Birthdate=system.today().addDays(-10),State__c='Az',SSN__c='454',Phone_Extension__c='455',Salutation__c='mr',HomePhone='343454545454',HealthCloudGA__Gender__c='female',Gender__c='female',Zip_Code__c='89898',Legal_Rep_Condition_Check__c='true',AccountId = ac.Id);
        insert con;
        contact con1 = [SELECT Id,lastname,firstname,Email,Birthdate,Legal_Rep_First_Name__c,Street_Address__c,Medical_Assistant_Name__c,Fax,Medical_Assistant_Phone__c,Phone_Extension__c,Salutation__c,Legal_Rep_Last_Name__c,Legal_Rep_Phone__c,Legal_Rep_Condition_Check__c,State__c,SSN__c,Zip_Code__c,phone,HomePhone,HealthCloudGA__Gender__c,Gender__c,Legal_RepRelTypec__c,Legal_Rep_Rel_Other__c,Address_Line_2__c,City__c FROM contact WHERE LastName='testCon' LIMIT 1];
         Consent__c consent = new Consent__c(Contact_Record__c=con.id,Consent_Type__c='New Consent');
         insert consent;
        try {
            test.startTest(); 
                Test.setMock(HttpCalloutMock.class, new RestMock());
                DS_OPAFController ds = new DS_OPAFController();
                string Signer = DS_OPAFController.getEmbeddedSigningUrl('b1ab9d97-6bf0-4f5d-be2f-b6bc7a4d1be0', '');
            test.stopTest();
        }
        catch (Exception e) {
                system.assert(e.getMessage() != null);
         }
           
    }
    
    @isTest
    static void sendPatientEnvelope() {
         Account ac = new Account(name ='Grazitti') ;
        insert ac;
        
        Id contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        Contact con = new Contact(LastName ='testCon',FirstName='test',Email='test@gmail.com',recordtypeId=contactRecordTypeId,Street_Address__c='test',Address_Line_2__c='test',City__c='test',phone='343434343',Birthdate=system.today().addDays(-10),State__c='Az',SSN__c='454',Phone_Extension__c='455',Salutation__c='mr',HomePhone='343454545454',HealthCloudGA__Gender__c='female',Gender__c='female',Zip_Code__c='89898',Legal_Rep_Condition_Check__c='true',AccountId = ac.Id);
        insert con;
        contact con1 = [SELECT Id,lastname,firstname,Email,Birthdate,Legal_Rep_First_Name__c,Street_Address__c,Medical_Assistant_Name__c,Fax,Medical_Assistant_Phone__c,Phone_Extension__c,Salutation__c,Legal_Rep_Last_Name__c,Legal_Rep_Phone__c,Legal_Rep_Condition_Check__c,State__c,SSN__c,Zip_Code__c,phone,HomePhone,HealthCloudGA__Gender__c,Gender__c,Legal_RepRelTypec__c,Legal_Rep_Rel_Other__c,Address_Line_2__c,City__c FROM contact WHERE LastName='testCon' LIMIT 1];
         Consent__c consent = new Consent__c(Contact_Record__c=con.id,Consent_Type__c='New Consent');
         insert consent;
        try {
            test.startTest(); 
                Test.setMock(HttpCalloutMock.class, new RestMock());
                DS_OPAFController ds = new DS_OPAFController();
                DS_OPAFController.EnvelopeSendResponse Signer = DS_OPAFController.sendPatientEnvelope(con.Id);
            test.stopTest();
        }
        catch (Exception e) {
                system.assert(e.getMessage() != null);
         }
           
    }
    
    @isTest
    static void updatePatientConsent() {
         Account ac = new Account(name ='Grazitti') ;
        insert ac;
        
        Id contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        Contact con = new Contact(LastName ='testCon',FirstName='test',Email='test@gmail.com',recordtypeId=contactRecordTypeId,Street_Address__c='test',Address_Line_2__c='test',City__c='test',phone='343434343',Birthdate=system.today().addDays(-10),State__c='Az',SSN__c='454',Phone_Extension__c='455',Salutation__c='mr',HomePhone='343454545454',HealthCloudGA__Gender__c='female',Gender__c='female',Zip_Code__c='89898',Legal_Rep_Condition_Check__c='true',AccountId = ac.Id);
        insert con;
        contact con1 = [SELECT Id,lastname,firstname,Email,Birthdate,Legal_Rep_First_Name__c,Street_Address__c,Medical_Assistant_Name__c,Fax,Medical_Assistant_Phone__c,Phone_Extension__c,Salutation__c,Legal_Rep_Last_Name__c,Legal_Rep_Phone__c,Legal_Rep_Condition_Check__c,State__c,SSN__c,Zip_Code__c,phone,HomePhone,HealthCloudGA__Gender__c,Gender__c,Legal_RepRelTypec__c,Legal_Rep_Rel_Other__c,Address_Line_2__c,City__c FROM contact WHERE LastName='testCon' LIMIT 1];
         Consent__c consent = new Consent__c(Contact_Record__c=con.id,Consent_Type__c='New Consent');
         insert consent;
        try {
            test.startTest(); 
                DS_OPAFController ds = new DS_OPAFController();
                DS_OPAFController.updatePatientConsent(con.Id,'b1ab9d97-6bf0-4f5d-be2f-b6bc7a4d1be0', 'signing_complete');
            test.stopTest();
        }
        catch (Exception e) {
                system.assert(e.getMessage() != null);
         }
           
    }
    
    @isTest
    static void sendLegalEnvelope() {
         Account ac = new Account(name ='Grazitti') ;
        insert ac;
        
        Id contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        Contact con = new Contact(LastName ='testCon',FirstName='test',Email='test@gmail.com',recordtypeId=contactRecordTypeId,Street_Address__c='test',Address_Line_2__c='test',City__c='test',phone='343434343',Birthdate=system.today().addDays(-10),State__c='Az',SSN__c='454',Phone_Extension__c='455',Salutation__c='mr',HomePhone='343454545454',HealthCloudGA__Gender__c='female',Gender__c='female',Zip_Code__c='89898',Legal_Rep_Condition_Check__c='true',AccountId = ac.Id);
        insert con;
        contact con1 = [SELECT Id,lastname,firstname,Email,Birthdate,Legal_Rep_First_Name__c,Street_Address__c,Medical_Assistant_Name__c,Fax,Medical_Assistant_Phone__c,Phone_Extension__c,Salutation__c,Legal_Rep_Last_Name__c,Legal_Rep_Phone__c,Legal_Rep_Condition_Check__c,State__c,SSN__c,Zip_Code__c,phone,HomePhone,HealthCloudGA__Gender__c,Gender__c,Legal_RepRelTypec__c,Legal_Rep_Rel_Other__c,Address_Line_2__c,City__c FROM contact WHERE LastName='testCon' LIMIT 1];
         Consent__c consent = new Consent__c(Contact_Record__c=con.id,Consent_Type__c='New Consent');
         insert consent;
        try {
            test.startTest(); 
                Test.setMock(HttpCalloutMock.class, new RestMock());
                DS_OPAFController ds = new DS_OPAFController();
                DS_OPAFController.EnvelopeSendResponse Signer = DS_OPAFController.sendLegalEnvelope(con.Id);
            test.stopTest();
        }
        catch (Exception e) {
                system.assert(e.getMessage() != null);
         }
           
    }
    
}