OpafProjectVfMods/force-app/main/default/objects/Case/fields/Enrollment_Status__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Status__c</fullName>
    <label>Enrollment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Missing Information</fullName>
            </value>
            <value>
                <fullName>Denied by Mail</fullName>
            </value>
            <value>
                <fullName>Denied by Phone</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pre-Qualified</fullName>
            </value>
            <value>
                <fullName>Saved to Complete Later</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Case/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Facilitys</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Case/fields/Prescriber__c.field-meta.xml
<CustomField>
    <fullName>Prescriber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prescriber</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Provider)</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Prescriber</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <label>Shipment</label>
    <nameField>
        <displayFormat>SH-{000000}</displayFormat>
        <label>Shipment  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OpafProjectVisualForcePages/force-app/main/default/objects/Shipment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Portal Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Shipment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <formula>Case__r.Patient__r.FirstName + &apos; &apos; +  Case__r.Patient__r.LastName</formula>
    <label>Patient</label>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Shipment__c/fields/Track_Shipment__c.field-meta.xml
<CustomField>
    <fullName>Track_Shipment__c</fullName>
    <formula>If(NOT(ISBLANK(Tracking_Number__c)),
HYPERLINK(&apos;https://www.fedex.com/fedextrack/no-results-found?trknbr=&apos;+ Tracking_Number__c, Tracking_Number__c) ,&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Track Shipment</label>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Shipment__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <label>User Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/classes/PatientEmailTempalteController.cls
public class PatientEmailTempalteController {
    public string CaseId{get;set;}
    public string ShipmentId{get;set;}
    //public Shipment__c Shipment{get;set;}
    public list<case> caselist = new  list<case>();
    public PatientEmailTempalteController(){
        
    }
    public shipment__c getShipment(){
        return [Select id,Case__r.Patient__r.FirstName,Case__r.Patient__r.Lastname,Case__r.Prescriber__r.email,case__r.Prescriber__r.Salutation, case__r.Prescriber__r.LastName,Track_Shipment__c,Tracking_Number__c,case__r.Prescriber__r.Name from Shipment__c where id=:ShipmentId];
        
        //return null;
    }
    public list<case> getcasereclist(){
        caselist = [select id,Enrollment_Status__c,User_Type__c,
                      Patient__c,
                      Patient__r.Firstname,
                      Patient__r.Lastname,
                      Patient__r.Email,
                      Patient__r.Phone,
                      Patient__r.fax,
                      Prescriber__r.name,
                      Prescriber__r.firstname,
                      Prescriber__r.Lastname,
                   	  Prescriber__r.Email,
                      prescriber__r.Salutation,
                      Prescriber__r.Phone,
                      Facility__c,
                      Facility__r.Name
                    from case where Id=:CaseId ];
        if (caselist.size()>0){
        return caselist;
        }
        return null;
    }

}