OpafProjectVfMods/force-app/main/default/objects/Case/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABILIFY_ASIMTUFII</fullName>
                <label>ABILIFY ASIMTUFII</label>
            </value>
            <value>
                <fullName>ABILIFY_MAINTENA</fullName>
                <label>ABILIFY MAINTENA</label>
            </value>
            <value>
                <fullName>JYNARQUE</fullName>
            </value>
            <value>
                <fullName>REXULTI</fullName>
            </value>
            <value>
                <fullName>SAMSCA</fullName>
            </value>
            <value>
                <fullName>NUEDEXTA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/classes/OPAF_NeuroscienceEnrollmentController.cls
public class OPAF_NeuroscienceEnrollmentController {
 public string CaseRecId {get;set;}
    public OPAF_NeuroscienceEnrollmentController(ApexPages.StandardController stdcontroller){
        CaseRecId = ApexPages.currentPage().getParameters().get('id') ;
        Case caserecord = [select id,Patient__c,Patient__r.Firstname,Patient__r.LastName,Product__c from Case where Id =:CaseRecId];
        String generatedFileName = 'Rx-'+caserecord.Product__c+'-'+caserecord.Patient__r.Firstname+caserecord.Patient__r.LastName+'.pdf';
        Apexpages.currentPage().getHeaders().put('content-disposition', 'attachment; filename=' +generatedFileName);
        
        //PageReference ref = new PageReference('https://partial-opaf.cs201.force.com/Prescriber/apex/eFaxCoversheet');
        /*PageReference ref = new PageReference('https://partial-opaf.cs201.force.com/apex/eFaxCoversheet');
              
        ContentVersion cont = new ContentVersion();
            cont.Title = 'Title for this contentVersion';
            cont.PathOnClient = 'file.pdf';
            cont.VersionData = ref.getContentAsPdf();
            //cont.Origin = 'H';
            cont.Document_Type__c='Coversheet';

            insert cont; */
    }
}