OpafProjectVisualForcePages/force-app/main/default/objects/Case/fields/Enrollment_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_End_Date__c</fullName>
    <label>Enrollment End Date</label>
    <type>Date</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/Enrollment_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Start_Date__c</fullName>
    <label>Enrollment Start Date</label>
    <type>Date</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Case/fields/Missing_Info__c.field-meta.xml
<CustomField>
    <fullName>Missing_Info__c</fullName>
    <label>Missing Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/Prescriber_DEA__c.field-meta.xml
<CustomField>
    <fullName>Prescriber_DEA__c</fullName>
    <description>Formula field from Prescriber record</description>
    <formula>Patient__r.DEA__c</formula>
    <inlineHelpText>Formula field from Prescriber record</inlineHelpText>
    <label>Prescriber DEA #</label>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Consent__c/Consent__c.object-meta.xml
<CustomObject>
    <label>Consent</label>
    <nameField>
        <displayFormat>CON-{000000}</displayFormat>
        <label>Consent</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OpafProjectVfMods/force-app/main/default/objects/Consent__c/fields/Consent_Type__c.field-meta.xml
<CustomField>
    <fullName>Consent_Type__c</fullName>
    <label>Consent Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Consent</fullName>
            </value>
            <value>
                <fullName>Re-Enrollment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Consent__c/fields/Contact_Record__c.field-meta.xml
<CustomField>
    <fullName>Contact_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Record</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consent</relationshipLabel>
    <relationshipName>Consent</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Consent__c/fields/EnvelopeId__c.field-meta.xml
<CustomField>
    <fullName>EnvelopeId__c</fullName>
    <label>EnvelopeId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <inlineHelpText>Custom Gender field non HC</inlineHelpText>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Contact/fields/HealthCloudGA__Gender__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Decline to Specify</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Contact/fields/HealthCloudGA__IndividualType__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__IndividualType__c</fullName>
    <description>Individual Type</description>
    <label>Individual Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
                <default>true</default>
                <label>Individual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Contact/fields/Legal_Rep_Condition_Check__c.field-meta.xml
<CustomField>
    <fullName>Legal_Rep_Condition_Check__c</fullName>
    <label>Legal Rep Condition Check</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>true</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Contact/fields/Medical_Assistant_Name__c.field-meta.xml
<CustomField>
    <fullName>Medical_Assistant_Name__c</fullName>
    <label>Medical Assistant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Contact/fields/Medical_Assistant_Phone__c.field-meta.xml
<CustomField>
    <fullName>Medical_Assistant_Phone__c</fullName>
    <label>Medical Assistant Phone</label>
    <type>Phone</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Contact/fields/Phone_Extension__c.field-meta.xml
<CustomField>
    <fullName>Phone_Extension__c</fullName>
    <label>Phone Extension</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Contact/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Contact/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <label>SSN</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Contact/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/Missing_Info__c.object-meta.xml
<CustomObject>
    <label>Missing Information</label>
    <nameField>
        <label>Missing Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missing Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Missing Informations</relationshipLabel>
    <relationshipName>Missing_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Date_Of_Hospital_Admission__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Hospital_Admission__c</fullName>
    <label>Date Of Hospital Admission</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Date_of_Hospital_Discharge__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Hospital_Discharge__c</fullName>
    <label>Date of Hospital Discharge</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Demographics__c.field-meta.xml
<CustomField>
    <fullName>Demographics__c</fullName>
    <label>Demographics</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Diagnosis__c.field-meta.xml
<CustomField>
    <fullName>Diagnosis__c</fullName>
    <label>Diagnosis</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Dosage__c.field-meta.xml
<CustomField>
    <fullName>Dosage__c</fullName>
    <label>Dosage</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Dosage_Strength__c.field-meta.xml
<CustomField>
    <fullName>Dosage_Strength__c</fullName>
    <label>Dosage Strength</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Dr_Signature_Date__c.field-meta.xml
<CustomField>
    <fullName>Dr_Signature_Date__c</fullName>
    <label>Dr Signature Date</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Expenses__c.field-meta.xml
<CustomField>
    <fullName>Expenses__c</fullName>
    <label>Expenses</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Frequency_Days_supply__c.field-meta.xml
<CustomField>
    <fullName>Frequency_Days_supply__c</fullName>
    <label>Frequency/Days supply</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/HIPAA_Authorization__c.field-meta.xml
<CustomField>
    <fullName>HIPAA_Authorization__c</fullName>
    <label>HIPAA Authorization</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Household_Size__c.field-meta.xml
<CustomField>
    <fullName>Household_Size__c</fullName>
    <label>Household Size</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Income_Amount__c.field-meta.xml
<CustomField>
    <fullName>Income_Amount__c</fullName>
    <label>Income Amount</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Income_Documentation__c.field-meta.xml
<CustomField>
    <fullName>Income_Documentation__c</fullName>
    <label>Income Documentation</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Income_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Income_Expenses__c</fullName>
    <label>Income/Expenses</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <label>Insurance</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Insurance_Denial_Letter__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Denial_Letter__c</fullName>
    <label>Insurance Denial Letter</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Insurance_Termination_Letter__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Termination_Letter__c</fullName>
    <label>Insurance Termination Letter</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Medicaid_Denial_Letter__c.field-meta.xml
<CustomField>
    <fullName>Medicaid_Denial_Letter__c</fullName>
    <label>Medicaid Denial Letter</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Medicare_Part_D_Card__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Part_D_Card__c</fullName>
    <label>Medicare Part D Card</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/No_Prescription_Form__c.field-meta.xml
<CustomField>
    <fullName>No_Prescription_Form__c</fullName>
    <label>No Prescription Form</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/No_Quantity_Indicated__c.field-meta.xml
<CustomField>
    <fullName>No_Quantity_Indicated__c</fullName>
    <label>No Quantity Indicated</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/NPI_Number__c.field-meta.xml
<CustomField>
    <fullName>NPI_Number__c</fullName>
    <label>NPI Number</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Number_of_Refills__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Refills__c</fullName>
    <label>Number of Refills</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Number_of_Vials__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Vials__c</fullName>
    <label>Number of Vials</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Patient_Signature__c.field-meta.xml
<CustomField>
    <fullName>Patient_Signature__c</fullName>
    <label>Patient Signature</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Patient_Signature_Date__c.field-meta.xml
<CustomField>
    <fullName>Patient_Signature_Date__c</fullName>
    <label>Patient Signature Date</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Prescriber_DEA__c.field-meta.xml
<CustomField>
    <fullName>Prescriber_DEA__c</fullName>
    <label>Prescriber DEA</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <label>Shipment</label>
    <nameField>
        <displayFormat>SH-{000000}</displayFormat>
        <label>Shipment  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OpafProjectVisualForcePages/force-app/main/default/objects/Shipment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Portal Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/User/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/classes/myWorkSpaceLWCControllerTest.cls
@isTest
private class myWorkSpaceLWCControllerTest {
    
    @testSetup static void setup() {
        
        
        Account ac = new Account(name ='Grazitti') ;
        insert ac;
        
        Id contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        Contact con = new Contact(LastName ='testCon',FirstName='test',Email='test@gmail.com',recordtypeId=contactRecordTypeId,Street_Address__c='test',HealthCloudGA__IndividualType__c='Prescriber',Medical_Assistant_Phone__c='4343434343',fax='5454545',Medical_Assistant_Name__c='test',Address_Line_2__c='test',City__c='test',phone='343434343',Birthdate=system.today().addDays(-10),State__c='Az',SSN__c='454',Phone_Extension__c='455',Salutation__c='mr',HomePhone='343454545454',HealthCloudGA__Gender__c='female',Gender__c='female',Zip_Code__c='89898',Legal_Rep_Condition_Check__c='true',AccountId = ac.Id);
        insert con;
        
        Id p = [select id from profile where name='Customer Community Plus Login User Custom'].id;
        
        User use = new User(alias = 'test123', email='test123@noemail.com',
                            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                            localesidkey='en_US', profileid = p, country='United States',IsActive =true,
                            ContactId = con.Id,
                            timezonesidkey='America/Los_Angeles', username='tester@noemail.com');
        insert use;
        System.runAs(use) {
            
            Consent__c consent = new Consent__c(Contact_Record__c=con.id,Consent_Type__c='New Consent',EnvelopeId__c='Test Id');
            insert consent;
        }
            
            //create common test cases
            List<case> testCases = new List<Case>();
            for(Integer i=0;i<2;i++) {
                testCases.add(new case(contactid=con.id,Enrollment_Start_Date__c = system.today().addDays(-10),Enrollment_End_Date__c = system.today().addDays(10)));
            }
        System.runAs(use) {
            insert testCases;
        }
            
            List<Shipment__c> shipList = new List<Shipment__c>();
            for(Integer i=0;i<2;i++) {
                shipList.add(new Shipment__c(case__c=testCases[0].id));
            }
            insert shipList;
            
            List<Missing_Info__c> MissingInfoList = new List<Missing_Info__c>();
            for(Integer i=0;i<2;i++) {
                MissingInfoList.add(new Missing_Info__c(case__c=testCases[0].id,Date_Of_Hospital_Admission__c='Y',Date_of_Hospital_Discharge__c='Y',Demographics__c='Y',
                                                        Diagnosis__c='Y',Dosage__c='Y',Dosage_Strength__c='Y',Dr_Signature_Date__c='Y',Expenses__c='Y',Frequency_Days_supply__c='Y',
                                                        HIPAA_Authorization__c='Y',Household_Size__c='Y',Income_Expenses__c='Y',Income_Amount__c='Y',Income_Documentation__c='Y',
                                                        Insurance__c='Y',Insurance_Denial_Letter__c='Y',Insurance_Termination_Letter__c='Y',Medicaid_Denial_Letter__c='Y',Medicare_Part_D_Card__c='Y',
                                                        No_Prescription_Form__c='Y',No_Quantity_Indicated__c='Y',NPI_Number__c='Y',Number_of_Refills__c='Y',Number_of_Vials__c='Y',
                                                        Patient_Signature__c='Y',Patient_Signature_Date__c='Y',Prescriber_DEA__c='Y',Prescriber_Signature__c='Y',Prescriber_SLN__c='Y',
                                                        Provider_Income_Attestation__c='Y',Provider_Insurance_Attestation__c='Y',Provider_Signature__c='Y',Reenrollment_Request__c='Y',
                                                        REMS_Enrollment__c='Y',Residency__c='Y',Underinsured_Policy__c='Y'));
            }
            insert MissingInfoList;
            
            //Create Document
            ContentVersion cv = new ContentVersion();
            cv.Title = 'Test Document';
            cv.PathOnClient = 'TestDocument.pdf';
            cv.VersionData = Blob.valueOf('Test Content');
            cv.IsMajorVersion = true;
            Insert cv;
            
            //Get Content Version
            List<ContentVersion> cvList = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id];
            System.assertEquals(cvList.size(), 1);
            
            //Get Content Documents
            List<ContentDocument> cdList = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
            System.assertEquals(cdList.size(), 1);
   
    }
    
    @isTest 
    static void testMethod1() {
        user use=[select id,name from user limit 1];
        contact con = [SELECT Id,HealthCloudGA__IndividualType__c,lastname,firstname,Email,Birthdate,Legal_Rep_First_Name__c,Street_Address__c,Medical_Assistant_Name__c,Fax,Medical_Assistant_Phone__c,Phone_Extension__c,Salutation__c,Legal_Rep_Last_Name__c,Legal_Rep_Phone__c,Legal_Rep_Condition_Check__c,State__c,SSN__c,Zip_Code__c,phone,HomePhone,HealthCloudGA__Gender__c,Gender__c,Legal_RepRelTypec__c,Legal_Rep_Rel_Other__c,Address_Line_2__c,City__c FROM contact WHERE LastName='testCon' LIMIT 1];
        
        Case cs= [SELECT Id FROM Case LIMIT 1];
        List<String> envelopeIds = new List<String>();
        envelopeIds.add('Test Id');
        Consent__c cn = [select id, EnvelopeId__c from Consent__c];
        ContactShare objContactShare = new ContactShare();
        objContactShare.ContactAccessLevel = 'Edit';
        objContactShare.ContactId = con.Id;
        objContactShare.RowCause = 'Manual';
        objContactShare.UserOrGroupId = use.id;
        //insert objContactShare;
        
        ContentDocument cd = [select id from ContentDocument limit 1];
        DocumentUploadController.FileInfo empW = new DocumentUploadController.FileInfo();
        //Create Document
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        cv.Document_Type__c ='Coversheet';
        Insert cv;
        set<id> conVersionIds = new set<Id>();
        conVersionIds.add(cv.id);
        
        //Get Content Documents
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
        
        System.debug('*****contentDocument***'+conDocId);
        //Create ContentDocumentLink 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = cs.Id;
        cdl.ContentDocumentId = conDocId;
        cdl.shareType = 'V';
        Insert cdl;
        
        
        system.debug(cdl.LinkedEntityId+'******'+cdl.ContentDocumentId+'*****'+cdl);
        empW.Title ='test';
        empW.DocumentType='text';
        empW.VersionData=Blob.valueOf('Test Content');
        
        
        String jsonVal ='{"Title":"","VersionData":"","DocumentType":""}' ; 
        List<Object> jsonList = new List<Object>();
        jsonList.add(empW);
        
        List<Object> caseJsonList = new List<object>();
        caseJsonList.add(cs);
        system.runAs(use) {
            myWorkSpaceLWCController.getCaseList();
            myWorkSpaceLWCController.getShipmentList(cs.id);
            myWorkSpaceLWCController.getMissingInfo(cs.id);
            myWorkSpaceLWCController.getCasebyEnrollmentStartDate(cs.id);
            myWorkSpaceLWCController.createCaseRecord();
            
            //PatientConsentController.getCurrentUserContact();
            PatientConsentController.updateContact(con,'Paper Consent',jsonList);
            try{
            PatientConsentController.updateConsent1(cn.Id, 'b1ab9d97-6bf0-4f5d-be2f-b6bc7a4d1be0');
            PatientConsentController.getCurrentUserContact();
            }
            catch(exception e){}
            
            OPAFApplicationFormController.getAllDocuments(con.id);
            OPAFApplicationFormController.deleteFile(cd.Id);
            OPAFApplicationFormController.getPrescriberContact(con.id);
            OPAFApplicationFormController.updateContact(con);
            try{
             OPAFApplicationFormController.createContact(cs.id,con,'StepOne');
            }
            catch(Exception e){
            }
            OPAFApplicationFormController.updateCase(cs,jsonList,'StepOne',con.id);
            OPAFApplicationFormController.updateCase(cs,jsonList,'YES',con.id);
            case caseInsert = new Case();
            caseInsert.contactid=con.id;
            caseInsert.Enrollment_Start_Date__c = system.today().addDays(-10);
            caseInsert.Enrollment_End_Date__c = system.today().addDays(10);
            OPAFApplicationFormController.updateCase(caseInsert,jsonList,'YES',con.id);
            
            OPAFApplicationFormController.insertPDF(cs.id);
            OPAFApplicationFormController.sendAllDocument(cs.id);
            OPAFApplicationFormController.getAllProductValues();
            OPAFApplicationFormController.getAllStateValues();
            //OPAFApplicationFormController.getCurrentUserContact();
            OPAFApplicationFormController.getCaseDetails(cs.id,'ReEnroll');
            
            
            PrescriberPatientConsentController.getContactDetails(con.id);
            PrescriberPatientConsentController.deleteFile(cd.id);
            PrescriberPatientConsentController.getAllDocuments(con.id);
            //PrescriberPatientConsentController.getCurrentUserContact();
            PrescriberPatientConsentController.updateConsent1(con.id,'4747-587857-45485');
            PrescriberPatientConsentController.updateNewContact(con,con.id,true,true,'Onsite',jsonList);
            PrescriberPatientConsentController.updateNewContact(con,con.id,true,true,'Paper',jsonList);
            PrescriberPatientConsentController.updateNewContact(con,con.id,true,true,'Email',jsonList);
            PrescriberPatientConsentController.updateEmailConsent(envelopeIds);
            PrescriberPatientConsentController.createForm(envelopeIds);
            
        }
        
        
    }
    
}