OpafProjectVisualForcePages/force-app/main/default/objects/Case/fields/Enrollment_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_End_Date__c</fullName>
    <label>Enrollment End Date</label>
    <type>Date</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/Enrollment_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Start_Date__c</fullName>
    <label>Enrollment Start Date</label>
    <type>Date</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Case/fields/Missing_Info__c.field-meta.xml
<CustomField>
    <fullName>Missing_Info__c</fullName>
    <label>Missing Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/Prescriber_DEA__c.field-meta.xml
<CustomField>
    <fullName>Prescriber_DEA__c</fullName>
    <description>Formula field from Prescriber record</description>
    <formula>Patient__r.DEA__c</formula>
    <inlineHelpText>Formula field from Prescriber record</inlineHelpText>
    <label>Prescriber DEA #</label>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Consent__c/Consent__c.object-meta.xml
<CustomObject>
    <label>Consent</label>
    <nameField>
        <displayFormat>CON-{000000}</displayFormat>
        <label>Consent</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OpafProjectVfMods/force-app/main/default/objects/Consent__c/fields/Consent_Type__c.field-meta.xml
<CustomField>
    <fullName>Consent_Type__c</fullName>
    <label>Consent Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Consent</fullName>
            </value>
            <value>
                <fullName>Re-Enrollment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Consent__c/fields/Contact_Record__c.field-meta.xml
<CustomField>
    <fullName>Contact_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Record</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consent</relationshipLabel>
    <relationshipName>Consent</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/Missing_Info__c.object-meta.xml
<CustomObject>
    <label>Missing Information</label>
    <nameField>
        <label>Missing Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missing Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Missing Informations</relationshipLabel>
    <relationshipName>Missing_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Date_Of_Hospital_Admission__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Hospital_Admission__c</fullName>
    <label>Date Of Hospital Admission</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Date_of_Hospital_Discharge__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Hospital_Discharge__c</fullName>
    <label>Date of Hospital Discharge</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Demographics__c.field-meta.xml
<CustomField>
    <fullName>Demographics__c</fullName>
    <label>Demographics</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Diagnosis__c.field-meta.xml
<CustomField>
    <fullName>Diagnosis__c</fullName>
    <label>Diagnosis</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Dosage__c.field-meta.xml
<CustomField>
    <fullName>Dosage__c</fullName>
    <label>Dosage</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Dosage_Strength__c.field-meta.xml
<CustomField>
    <fullName>Dosage_Strength__c</fullName>
    <label>Dosage Strength</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Dr_Signature_Date__c.field-meta.xml
<CustomField>
    <fullName>Dr_Signature_Date__c</fullName>
    <label>Dr Signature Date</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Expenses__c.field-meta.xml
<CustomField>
    <fullName>Expenses__c</fullName>
    <label>Expenses</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Frequency_Days_supply__c.field-meta.xml
<CustomField>
    <fullName>Frequency_Days_supply__c</fullName>
    <label>Frequency/Days supply</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/HIPAA_Authorization__c.field-meta.xml
<CustomField>
    <fullName>HIPAA_Authorization__c</fullName>
    <label>HIPAA Authorization</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Household_Size__c.field-meta.xml
<CustomField>
    <fullName>Household_Size__c</fullName>
    <label>Household Size</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Income_Amount__c.field-meta.xml
<CustomField>
    <fullName>Income_Amount__c</fullName>
    <label>Income Amount</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Income_Documentation__c.field-meta.xml
<CustomField>
    <fullName>Income_Documentation__c</fullName>
    <label>Income Documentation</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Income_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Income_Expenses__c</fullName>
    <label>Income/Expenses</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <label>Insurance</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Insurance_Denial_Letter__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Denial_Letter__c</fullName>
    <label>Insurance Denial Letter</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Insurance_Termination_Letter__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Termination_Letter__c</fullName>
    <label>Insurance Termination Letter</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Medicaid_Denial_Letter__c.field-meta.xml
<CustomField>
    <fullName>Medicaid_Denial_Letter__c</fullName>
    <label>Medicaid Denial Letter</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Medicare_Part_D_Card__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Part_D_Card__c</fullName>
    <label>Medicare Part D Card</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/No_Prescription_Form__c.field-meta.xml
<CustomField>
    <fullName>No_Prescription_Form__c</fullName>
    <label>No Prescription Form</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/No_Quantity_Indicated__c.field-meta.xml
<CustomField>
    <fullName>No_Quantity_Indicated__c</fullName>
    <label>No Quantity Indicated</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/NPI_Number__c.field-meta.xml
<CustomField>
    <fullName>NPI_Number__c</fullName>
    <label>NPI Number</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Number_of_Refills__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Refills__c</fullName>
    <label>Number of Refills</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Number_of_Vials__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Vials__c</fullName>
    <label>Number of Vials</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Patient_Signature__c.field-meta.xml
<CustomField>
    <fullName>Patient_Signature__c</fullName>
    <label>Patient Signature</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Patient_Signature_Date__c.field-meta.xml
<CustomField>
    <fullName>Patient_Signature_Date__c</fullName>
    <label>Patient Signature Date</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Prescriber_DEA__c.field-meta.xml
<CustomField>
    <fullName>Prescriber_DEA__c</fullName>
    <label>Prescriber DEA</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Prescriber_Signature__c.field-meta.xml
<CustomField>
    <fullName>Prescriber_Signature__c</fullName>
    <label>Prescriber Signature</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Prescriber_SLN__c.field-meta.xml
<CustomField>
    <fullName>Prescriber_SLN__c</fullName>
    <label>Prescriber SLN</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Provider_Income_Attestation__c.field-meta.xml
<CustomField>
    <fullName>Provider_Income_Attestation__c</fullName>
    <label>Provider Income Attestation</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Provider_Insurance_Attestation__c.field-meta.xml
<CustomField>
    <fullName>Provider_Insurance_Attestation__c</fullName>
    <label>Provider Insurance Attestation</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Provider_Signature__c.field-meta.xml
<CustomField>
    <fullName>Provider_Signature__c</fullName>
    <label>Provider Signature</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Reenrollment_Request__c.field-meta.xml
<CustomField>
    <fullName>Reenrollment_Request__c</fullName>
    <label>Re-enrollment Request</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/REMS_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>REMS_Enrollment__c</fullName>
    <label>REMS Enrollment</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Residency__c.field-meta.xml
<CustomField>
    <fullName>Residency__c</fullName>
    <label>Residency</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Underinsured_Policy__c.field-meta.xml
<CustomField>
    <fullName>Underinsured_Policy__c</fullName>
    <label>Underinsured Policy</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <label>Shipment</label>
    <nameField>
        <displayFormat>SH-{000000}</displayFormat>
        <label>Shipment  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OpafProjectVisualForcePages/force-app/main/default/objects/Shipment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Portal Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/classes/DocumentUploadControllerTest.cls
@isTest
private class DocumentUploadControllerTest {
    
    @testSetup static void setup() {
        
        Account ac = new Account(name ='Grazitti') ;
        insert ac;
        
        Contact con = new Contact(LastName ='testCon',AccountId = ac.Id);
        insert con;
        Consent__c consent = new Consent__c(Contact_Record__c=con.id,Consent_Type__c='New Consent');
        insert consent;
        
        //create common test cases
        List<case> testCases = new List<Case>();
        for(Integer i=0;i<2;i++) {
           testCases.add(new case(contactid=con.id,Enrollment_Start_Date__c = system.today().addDays(-10),Enrollment_End_Date__c = system.today().addDays(10)));
        }
        insert testCases;
        
        List<Shipment__c> shipList = new List<Shipment__c>();
        for(Integer i=0;i<2;i++) {
           shipList.add(new Shipment__c(case__c=testCases[0].id));
        }
        insert shipList;
        
        List<Missing_Info__c> MissingInfoList = new List<Missing_Info__c>();
        for(Integer i=0;i<2;i++) {
           MissingInfoList.add(new Missing_Info__c(case__c=testCases[0].id,Date_Of_Hospital_Admission__c='Y',Date_of_Hospital_Discharge__c='Y',Demographics__c='Y',
                                                   Diagnosis__c='Y',Dosage__c='Y',Dosage_Strength__c='Y',Dr_Signature_Date__c='Y',Expenses__c='Y',Frequency_Days_supply__c='Y',
                                                   HIPAA_Authorization__c='Y',Household_Size__c='Y',Income_Expenses__c='Y',Income_Amount__c='Y',Income_Documentation__c='Y',
                                                   Insurance__c='Y',Insurance_Denial_Letter__c='Y',Insurance_Termination_Letter__c='Y',Medicaid_Denial_Letter__c='Y',Medicare_Part_D_Card__c='Y',
                                                   No_Prescription_Form__c='Y',No_Quantity_Indicated__c='Y',NPI_Number__c='Y',Number_of_Refills__c='Y',Number_of_Vials__c='Y',
                                                   Patient_Signature__c='Y',Patient_Signature_Date__c='Y',Prescriber_DEA__c='Y',Prescriber_Signature__c='Y',Prescriber_SLN__c='Y',
                                                   Provider_Income_Attestation__c='Y',Provider_Insurance_Attestation__c='Y',Provider_Signature__c='Y',Reenrollment_Request__c='Y',
                                                   REMS_Enrollment__c='Y',Residency__c='Y',Underinsured_Policy__c='Y'));
        }
        insert MissingInfoList;
        
        
        
    }
    @isTest static void testMethod1() {
       contact con = [SELECT Id FROM contact WHERE LastName='testCon' LIMIT 1];
       //Create Document
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        Insert cv;
        set<id> conVersionIds = new set<Id>();
        conVersionIds.add(cv.id);
         
        //Get Content Documents
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
         
        //Create ContentDocumentLink 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = con.Id;
        cdl.ContentDocumentId = conDocId;
        cdl.shareType = 'V';
        Insert cdl;
        DocumentUploadController.FileInfo empW = new DocumentUploadController.FileInfo();
        empW.Title ='test';
        empW.DocumentType='text';
        empW.VersionData=Blob.valueOf('Test Content');
        
        contentVersion cv1 = new contentVersion();
        cv1.VersionData=empW.VersionData;
        cv1.Title = empW.Title;
        cv1.PathOnClient = empW.Title;
        cv1.Document_Type__c = empW.DocumentType;
        insert cv1;
        
        String jsonVal ='{"Title":"","VersionData":"","DocumentType":""}' ; 
        List<Object> jsonList = new List<Object>();
        jsonList.add(empW);
        
        //string str= DocumentUploadController.FileInfo(jsonVal);

        DocumentUploadController.getAllDocuments(con.id);
        DocumentUploadController.createContentLink(conVersionIds,con.id);
        DocumentUploadController.createContentVersion(jsonList,con.id);
    }
}