OpafProjectVisualForcePages/force-app/main/default/objects/Case/fields/Enrollment_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_End_Date__c</fullName>
    <label>Enrollment End Date</label>
    <type>Date</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/Enrollment_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Start_Date__c</fullName>
    <label>Enrollment Start Date</label>
    <type>Date</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/Enrollment_Status__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Status__c</fullName>
    <label>Enrollment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Missing Information</fullName>
            </value>
            <value>
                <fullName>Denied by Mail</fullName>
            </value>
            <value>
                <fullName>Denied by Phone</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pre-Qualified</fullName>
            </value>
            <value>
                <fullName>Saved to Complete Later</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Case/fields/Missing_Info__c.field-meta.xml
<CustomField>
    <fullName>Missing_Info__c</fullName>
    <label>Missing Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Case/fields/Prescriber__c.field-meta.xml
<CustomField>
    <fullName>Prescriber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prescriber</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Provider)</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/Prescriber_DEA__c.field-meta.xml
<CustomField>
    <fullName>Prescriber_DEA__c</fullName>
    <description>Formula field from Prescriber record</description>
    <formula>Patient__r.DEA__c</formula>
    <inlineHelpText>Formula field from Prescriber record</inlineHelpText>
    <label>Prescriber DEA #</label>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABILIFY_ASIMTUFII</fullName>
                <label>ABILIFY ASIMTUFII</label>
            </value>
            <value>
                <fullName>ABILIFY_MAINTENA</fullName>
                <label>ABILIFY MAINTENA</label>
            </value>
            <value>
                <fullName>JYNARQUE</fullName>
            </value>
            <value>
                <fullName>REXULTI</fullName>
            </value>
            <value>
                <fullName>SAMSCA</fullName>
            </value>
            <value>
                <fullName>NUEDEXTA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Case/fields/Saved_Location__c.field-meta.xml
<CustomField>
    <fullName>Saved_Location__c</fullName>
    <label>Saved Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Consent__c/Consent__c.object-meta.xml
<CustomObject>
    <label>Consent</label>
    <nameField>
        <displayFormat>CON-{000000}</displayFormat>
        <label>Consent</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OpafProjectVfMods/force-app/main/default/objects/Consent__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <inlineHelpText>Select the product that you are submitting your application for</inlineHelpText>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABILIFY MAINTENA</fullName>
            </value>
            <value>
                <fullName>JYNARQUE</fullName>
            </value>
            <value>
                <fullName>REXULTI</fullName>
            </value>
            <value>
                <fullName>SAMSCA</fullName>
            </value>
            <value>
                <fullName>ABILIFY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/Missing_Info__c.object-meta.xml
<CustomObject>
    <label>Missing Information</label>
    <nameField>
        <label>Missing Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Missing Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Missing Informations</relationshipLabel>
    <relationshipName>Missing_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Date_Of_Hospital_Admission__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Hospital_Admission__c</fullName>
    <label>Date Of Hospital Admission</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Date_of_Hospital_Discharge__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Hospital_Discharge__c</fullName>
    <label>Date of Hospital Discharge</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Demographics__c.field-meta.xml
<CustomField>
    <fullName>Demographics__c</fullName>
    <label>Demographics</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Diagnosis__c.field-meta.xml
<CustomField>
    <fullName>Diagnosis__c</fullName>
    <label>Diagnosis</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Dosage__c.field-meta.xml
<CustomField>
    <fullName>Dosage__c</fullName>
    <label>Dosage</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Dosage_Strength__c.field-meta.xml
<CustomField>
    <fullName>Dosage_Strength__c</fullName>
    <label>Dosage Strength</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Dr_Signature_Date__c.field-meta.xml
<CustomField>
    <fullName>Dr_Signature_Date__c</fullName>
    <label>Dr Signature Date</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Expenses__c.field-meta.xml
<CustomField>
    <fullName>Expenses__c</fullName>
    <label>Expenses</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Frequency_Days_supply__c.field-meta.xml
<CustomField>
    <fullName>Frequency_Days_supply__c</fullName>
    <label>Frequency/Days supply</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/HIPAA_Authorization__c.field-meta.xml
<CustomField>
    <fullName>HIPAA_Authorization__c</fullName>
    <label>HIPAA Authorization</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Household_Size__c.field-meta.xml
<CustomField>
    <fullName>Household_Size__c</fullName>
    <label>Household Size</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Income_Amount__c.field-meta.xml
<CustomField>
    <fullName>Income_Amount__c</fullName>
    <label>Income Amount</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Income_Documentation__c.field-meta.xml
<CustomField>
    <fullName>Income_Documentation__c</fullName>
    <label>Income Documentation</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Income_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Income_Expenses__c</fullName>
    <label>Income/Expenses</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <label>Insurance</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Insurance_Denial_Letter__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Denial_Letter__c</fullName>
    <label>Insurance Denial Letter</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Insurance_Termination_Letter__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Termination_Letter__c</fullName>
    <label>Insurance Termination Letter</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Medicaid_Denial_Letter__c.field-meta.xml
<CustomField>
    <fullName>Medicaid_Denial_Letter__c</fullName>
    <label>Medicaid Denial Letter</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Medicare_Part_D_Card__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Part_D_Card__c</fullName>
    <label>Medicare Part D Card</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/No_Prescription_Form__c.field-meta.xml
<CustomField>
    <fullName>No_Prescription_Form__c</fullName>
    <label>No Prescription Form</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/No_Quantity_Indicated__c.field-meta.xml
<CustomField>
    <fullName>No_Quantity_Indicated__c</fullName>
    <label>No Quantity Indicated</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/NPI_Number__c.field-meta.xml
<CustomField>
    <fullName>NPI_Number__c</fullName>
    <label>NPI Number</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Number_of_Refills__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Refills__c</fullName>
    <label>Number of Refills</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Missing_Info__c/fields/Number_of_Vials__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Vials__c</fullName>
    <label>Number of Vials</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Patient_Signature__c.field-meta.xml
<CustomField>
    <fullName>Patient_Signature__c</fullName>
    <label>Patient Signature</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Patient_Signature_Date__c.field-meta.xml
<CustomField>
    <fullName>Patient_Signature_Date__c</fullName>
    <label>Patient Signature Date</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Prescriber_DEA__c.field-meta.xml
<CustomField>
    <fullName>Prescriber_DEA__c</fullName>
    <label>Prescriber DEA</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Prescriber_Signature__c.field-meta.xml
<CustomField>
    <fullName>Prescriber_Signature__c</fullName>
    <label>Prescriber Signature</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Missing_Info__c/fields/Prescriber_SLN__c.field-meta.xml
<CustomField>
    <fullName>Prescriber_SLN__c</fullName>
    <label>Prescriber SLN</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <label>Shipment</label>
    <nameField>
        <displayFormat>SH-{000000}</displayFormat>
        <label>Shipment  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OpafProjectVisualForcePages/force-app/main/default/objects/Shipment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Portal Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Shipment__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>TEXT(Case__r.Product__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product</label>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Shipment__c/fields/Shipment_Status__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Status__c</fullName>
    <label>Shipment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/classes/myWorkSpaceLWCController.cls
public without sharing class myWorkSpaceLWCController {
    @AuraEnabled
    public static List<Case> getCaseList() {
        try {
            user userDetails = [select id,name,ContactId from user where Id =: userInfo.getUserId()];
            List<Case> cs = new List<Case>();
            cs = [SELECT Id,ContactId,CaseNumber,Saved_Location__c,
                  Prescriber__c,Status,Enrollment_End_Date__c,parent.Status,parent.Enrollment_Status__c,
                  parent.Enrollment_Start_Date__c,parent.Enrollment_End_Date__c,parent.Product__c,
                  Enrollment_Start_Date__c,Product__c,Parent.CaseNumber,ParentId,Enrollment_Status__c
                  FROM Case where ContactId =: userDetails.ContactId ORDER BY createdDate Desc limit 1];
            if(!cs.IsEmpty())
            {
                return cs;
            }
            else{
                return null;
            }
        } catch(Exception ex) {
            throw new AurahandledException(ex.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Shipment__c> getShipmentList(Id caseIdData) {
        try {
            List<Shipment__c> shipList = new List<Shipment__c>();
            shipList = [SELECT Id,Shipment_Status__c FROM Shipment__c where case__c =: caseIdData ORDER BY createdDate Desc limit 1];
            if(!shipList.IsEmpty())
                return shipList;
            else
                return null;
        } catch(Exception ex) {
            throw new AurahandledException(ex.getMessage());
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static string getMissingInfo(Id caseIdData) {
        try {
            string missingFieldsInfo='';
            system.debug('******'+caseIdData);
            
            List<Missing_Info__c> minfo = [SELECT Id,Date_Of_Hospital_Admission__c,Date_of_Hospital_Discharge__c,Demographics__c,Diagnosis__c,
                                           Dosage__c,Dosage_Strength__c,Dr_Signature_Date__c,Expenses__c,Frequency_Days_supply__c,HIPAA_Authorization__c,
                                           Household_Size__c,Income_Expenses__c,Income_Amount__c,Income_Documentation__c,Insurance__c,Insurance_Denial_Letter__c,
                                           Insurance_Termination_Letter__c,Medicaid_Denial_Letter__c,Medicare_Part_D_Card__c,No_Prescription_Form__c,No_Quantity_Indicated__c,
                                           NPI_Number__c,Number_of_Refills__c,Number_of_Vials__c,Patient_Signature__c,Patient_Signature_Date__c,Prescriber_DEA__c,
                                           Prescriber_Signature__c,Prescriber_SLN__c,Provider_Income_Attestation__c,Provider_Insurance_Attestation__c,Provider_Signature__c,
                                           Reenrollment_Request__c,REMS_Enrollment__c,Residency__c,Underinsured_Policy__c
                                           FROM Missing_Info__c where case__c =: caseIdData ORDER BY createdDate Desc limit 1];
            if(!minfo.isEmpty()) {
                if(minfo[0].Date_Of_Hospital_Admission__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Date Of Hospital Admission\n';
                }
                if(minfo[0].Date_of_Hospital_Discharge__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Date of Hospital Discharge\n';
                }
                if(minfo[0].Demographics__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Demographics\n';
                }
                if(minfo[0].Diagnosis__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Diagnosis\n';
                }
                if(minfo[0].Dosage__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Dosage\n';
                }
                if(minfo[0].Dosage_Strength__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Dosage Strength\n';
                }
                if(minfo[0].Dr_Signature_Date__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Dr Signature Date\n';
                }
                if(minfo[0].Expenses__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Expenses\n';
                }
                if(minfo[0].Frequency_Days_supply__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Frequency/Days supply\n';
                }
                if(minfo[0].HIPAA_Authorization__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'HIPAA Authorization\n';
                }
                if(minfo[0].Household_Size__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Household Size\n';
                }
                if(minfo[0].Income_Expenses__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Income/Expenses\n';
                }
                if(minfo[0].Income_Amount__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Income Amount\n';
                }
                if(minfo[0].Income_Documentation__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Income Documentation\n';
                }
                if(minfo[0].Insurance__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Insurance\n';
                }
                if(minfo[0].Insurance_Denial_Letter__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Insurance Denial Letter\n';
                }
                if(minfo[0].Insurance_Termination_Letter__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Insurance Termination Letter\n';
                }
                if(minfo[0].Medicaid_Denial_Letter__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Medicaid Denial Letter\n';
                }
                system.debug('******'+missingFieldsInfo);
                
                if(minfo[0].Medicare_Part_D_Card__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Medicare Part D Card\n';
                }
                if(minfo[0].No_Prescription_Form__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'No Prescription Form\n';
                }
                if(minfo[0].No_Quantity_Indicated__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'No Quantity Indicated\n';
                }
                if(minfo[0].NPI_Number__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'NPI Number\n';
                }
                if(minfo[0].Number_of_Refills__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Number of Refills\n';
                }
                if(minfo[0].Number_of_Vials__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Number of Vials\n';
                }
                if(minfo[0].Patient_Signature__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Patient Signature\n';
                }
                if(minfo[0].Patient_Signature_Date__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Patient Signature Date\n';
                }
                if(minfo[0].Prescriber_DEA__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Prescriber DEA\n';
                }
                if(minfo[0].Prescriber_Signature__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Prescriber Signature\n';
                }
                if(minfo[0].Prescriber_SLN__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Prescriber SLN\n';
                }
                if(minfo[0].Provider_Income_Attestation__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Provider Income Attestation\n';
                }
                if(minfo[0].Provider_Insurance_Attestation__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Provider Insurance Attestation\n';
                }
                if(minfo[0].Provider_Signature__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Provider Signature\n';
                }
                if(minfo[0].Reenrollment_Request__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Re-enrollment Request\n';
                }
                if(minfo[0].REMS_Enrollment__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'REMS Enrollment\n';
                }
                if(minfo[0].Residency__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Residency\n';
                }
                if(minfo[0].Underinsured_Policy__c =='Y'){
                    missingFieldsInfo = missingFieldsInfo +'-' + 'Underinsured Policy\n';
                }
            }
            return missingFieldsInfo;
        } catch(Exception ex) {
            throw new AurahandledException(ex.getMessage());
        }
        
    }
    
    @AuraEnabled(cacheable=true)
    public static String getCasebyEnrollmentStartDate(Id caseIdData) {
        try {
            Case cs = new Case();
            String enrollmentBoolean = '';
            cs = [SELECT Id,CaseNumber,Status,Enrollment_End_Date__c,Product__c,Enrollment_Status__c,Enrollment_Start_Date__c 
                  FROM Case where Id =: caseIdData];
            if(cs.id != null){
                Date startDate;
                if(cs.Enrollment_Start_Date__c != null){
                    startDate = cs.Enrollment_Start_Date__c;
                }
                
                Integer noOfDays = null;
                Date endDate ;
                if(cs.Enrollment_End_Date__c != null){
                    endDate = cs.Enrollment_End_Date__c;
                    noOfDays = System.today().daysBetween(endDate);
                }
                
                if(cs == null) {
                    enrollmentBoolean = 'newopaf';
                } else if(noOfDays != null && cs.Enrollment_Start_Date__c <= system.Today() && cs.Enrollment_End_Date__c >= system.today() && cs.Enrollment_Status__c == 'Enrolled' && noOfDays <= 45 && noOfDays >= 0){
                    enrollmentBoolean = 'reEnroll';
                    system.debug('*****hello****');
                }
                if(cs.Enrollment_Status__c == 'Saved to Complete Later'){
                    enrollmentBoolean = 'incompleteopf';
                }
            }
            
            return enrollmentBoolean;
        } catch(Exception ex) {
            throw new AurahandledException(ex.getMessage());
        }
    }
    @AuraEnabled
    public static string createCaseRecord(){
        try {
            case c = new case();
            c.Enrollment_Start_Date__c = system.today();
            c.Enrollment_End_Date__c = system.today().addDays(30);
            c.Origin = 'Phone';
            insert c;
            return c.id;
        } catch(Exception ex) {
            throw new AurahandledException(ex.getMessage());
        }
    }
    
    @auraEnabled(cacheable=true)
    public Static List<Consent__c> getCurrentUserContact(){
        try {
            user userDetails = [select id,name,ContactId from user where Id =: userInfo.getUserId()];
            List<Consent__c> contactDetail = [select id,Type__c,DocusignCheck__c from Consent__c where Patient__c =: userDetails.ContactId];
            if(contactDetail.isEmpty()) { return null; }
            return contactDetail;
        } catch(Exception ex) {
            throw new AurahandledException(ex.getMessage());
        }
    }
    
}