OpafProjectVisualForcePages/force-app/main/default/objects/Case/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Facilitys</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Case/fields/Hub_Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>Hub_Facility_ID__c</fullName>
    <formula>Facility__r.External_Facility_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hub Facility ID</label>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/Hub_Patient_ID__c.field-meta.xml
<CustomField>
    <fullName>Hub_Patient_ID__c</fullName>
    <formula>Patient__r.External_Patient_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hub Patient ID</label>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Case/fields/Hub_Provider_ID__c.field-meta.xml
<CustomField>
    <fullName>Hub_Provider_ID__c</fullName>
    <formula>Prescriber__r.External_Prescriber_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hub Provider ID</label>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Individual</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Case/fields/Prescriber__c.field-meta.xml
<CustomField>
    <fullName>Prescriber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prescriber</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Provider)</relationshipLabel>
    <relationshipName>Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABILIFY_ASIMTUFII</fullName>
                <label>ABILIFY ASIMTUFII</label>
            </value>
            <value>
                <fullName>ABILIFY_MAINTENA</fullName>
                <label>ABILIFY MAINTENA</label>
            </value>
            <value>
                <fullName>JYNARQUE</fullName>
            </value>
            <value>
                <fullName>REXULTI</fullName>
            </value>
            <value>
                <fullName>SAMSCA</fullName>
            </value>
            <value>
                <fullName>NUEDEXTA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/Rx_Fax_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Rx_Fax_Timestamp__c</fullName>
    <label>Rx Fax Timestamp</label>
    <type>DateTime</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Case/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Prescriber</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/User/fields/Legacy_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_User_Id__c</fullName>
    <externalId>true</externalId>
    <label>Legacy User Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/classes/eFaxCoverSheetController.cls
public class eFaxCoverSheetController {
    public Case caseRec {get;set;}
    public User portalUserDetails {get;set;}

    public string SalesforceRequestorID {get;set;}
    public eFaxCoverSheetController(){
        
    }
    public eFaxCoverSheetController(ApexPages.StandardController stdController) {
        this.caseRec = (case)stdController.getRecord();

        if(this.caseRec != null){
            
            this.caseRec = [SELECT Id, 
                                    CaseNumber, 
                                    User_Type__c,
                                    Patient__c,
                                    Hub_Patient_ID__c,
                                    ContactId,
                                    Prescriber__c,
                                    Hub_Provider_ID__c,
                                    Facility__c,
                                    Hub_Facility_ID__c,
                                    Product__c,
                                    Rx_Fax_Timestamp__c
                                    FROM 
                                    Case 
                                    WHERE 
                                    Id =: this.caseRec.Id];
            
            System.debug('the this.caseRec' + this.caseRec);

            if(this.caseRec.ContactId != null){

                SalesforceRequestorID = this.caseRec.ContactId;

                System.debug('the contact info is' + this.caseRec.ContactId);

                List<User> portalUserInfo = [SELECT  Id,
                                                        Legacy_User_Id__c	
                                                        FROM 
                                                        User 
                                                        WHERE 
                                                        ContactId =: this.caseRec.ContactId];
                
                System.debug('the portalUserInfo info is' + portalUserInfo);

                if(!portalUserInfo.isEmpty()){
                    portalUserDetails = portalUserInfo[0];
                }
            }
        }

    }
    public String getESTTime() {
       String estTime;
       if(caseRec.Rx_Fax_Timestamp__c==null)
       estTime = null;
       else
       estTime = (String)caseRec.Rx_Fax_Timestamp__c.format('MM/dd/yyy h:mm:ss a', 'America/New_York') + ' ET';
       return estTime;
    }

}