OpafProjectVisualForcePages/force-app/main/default/objects/Consent__c/Consent__c.object-meta.xml
<CustomObject>
    <label>Consent</label>
    <nameField>
        <displayFormat>CON-{000000}</displayFormat>
        <label>Consent</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OpafProjectVisualForcePages/force-app/main/default/objects/Consent__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consent (Patient)</relationshipLabel>
    <relationshipName>Consent1</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Consent__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prescriber</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consent (Provider)</relationshipLabel>
    <relationshipName>Consent2</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Contact/fields/External_Patient_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Patient_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Patient Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Contact/fields/External_Prescriber_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Prescriber_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Prescriber Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/User/fields/Legacy_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_User_Id__c</fullName>
    <externalId>true</externalId>
    <label>Legacy User Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/classes/eFaxCoverSheetConsentController.cls
public class eFaxCoverSheetConsentController {
    public Consent__c caseRec {get;set;}
    public User portalUserDetails {get;set;}

    public string SalesforceRequestorID {get;set;}
    public eFaxCoverSheetConsentController(ApexPages.StandardController stdController) {
        this.caseRec = (Consent__c)stdController.getRecord();

        if(this.caseRec != null){
            
            this.caseRec = [SELECT Id, 
                                    Name,
                            		Provider__c,
                            		Patient__c,
                            		Provider__r.External_Prescriber_Id__c,
                            		Patient__r.External_Patient_Id__c
                                    FROM 
                                    Consent__c 
                                    WHERE 
                                    Id =: this.caseRec.Id];
            
            System.debug('the this.caseRec' + this.caseRec);

            if(this.caseRec.Provider__c != null){

                SalesforceRequestorID = this.caseRec.Provider__c;

                System.debug('the contact info is' + this.caseRec.Provider__c);

                List<User> portalUserInfo = [SELECT  Id,
                                                        Legacy_User_Id__c	
                                                        FROM 
                                                        User 
                                                        WHERE 
                                                        ContactId =: this.caseRec.Provider__c];
                
                System.debug('the portalUserInfo info is' + portalUserInfo);

                if(!portalUserInfo.isEmpty()){
                    portalUserDetails = portalUserInfo[0];
                }
            }
        }

    }
    /*
    public String getESTTime() {
       String estTime;
       if(caseRec.Rx_Fax_Timestamp__c==null)
       estTime = null;
       else
       estTime = (String)caseRec.Rx_Fax_Timestamp__c.format('MM/dd/yyy h:mm:ss a', 'America/New_York') + ' ET';
       return estTime;
    }*/


}