OpafProjectVisualForcePages/force-app/main/default/objects/Consent__c/Consent__c.object-meta.xml
<CustomObject>
    <label>Consent</label>
    <nameField>
        <displayFormat>CON-{000000}</displayFormat>
        <label>Consent</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OpafProjectVfMods/force-app/main/default/objects/Consent__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Onsite</fullName>
            </value>
            <value>
                <fullName>Paper</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Consent__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consent (Patient)</relationshipLabel>
    <relationshipName>Consent1</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Consent__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/classes/SendDocuSignEmailBatch.cls
public class SendDocuSignEmailBatch implements
    Database.Batchable<sObject>, Database.AllowsCallouts {
    // instance member to retain state across transactions
    public Integer recordsProcessed = 0;
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'select Id,Status__c,Method__c,Patient__c from Consent__c where Method__c =\'Email\' and Status__c =\'Processing\' Order by Createddate desc limit 1' 
        );
    }
    public void execute(Database.BatchableContext bc, List<Consent__c> scope){
        // process each batch of records
        for (Consent__c consent : scope) {
            DS_OPAFController.sendPatientEnvelope(consent.Patient__c);
        }
        
    }
    public void finish(Database.BatchableContext bc){
        System.debug(recordsProcessed + ' records processed. Shazam!');
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors,
            JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :bc.getJobId()];
        // call some utility to send email
        //EmailUtils.sendMessage(job, recordsProcessed);
    }
}