OpafProjectVisualForcePages/force-app/main/default/objects/Consent__c/Consent__c.object-meta.xml
<CustomObject>
    <label>Consent</label>
    <nameField>
        <displayFormat>CON-{000000}</displayFormat>
        <label>Consent</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OpafProjectVfMods/force-app/main/default/objects/Consent__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prescriber</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consent (Provider)</relationshipLabel>
    <relationshipName>Consent2</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/classes/ConsentTriggerHandler.cls
public class ConsentTriggerHandler {
    public static void shareConsentToPrescriberOwner(List<Consent__c> consentList){
        set<Id> prescriberIds = new set<Id>();
        for(Consent__c c:consentList){
            if(c.Provider__c!=null){
            	prescriberIds.add(c.Provider__c);    
            }
            
        }
        map<Id, Contact> prescriberMap = new map<Id,Contact>([Select Id,OwnerId, Owner.Profile.Name from Contact where Id in:prescriberIds]);
        List<Consent__Share> consentShare = new List<Consent__Share>();
        for(Consent__c Consent:consentList){
            if(prescriberMap!=null  && Consent.Provider__c!=null &&  Consent.OwnerId!=prescriberMap.get(Consent.Provider__c).OwnerId && prescriberMap.get(Consent.Provider__c).Owner.Profile.Name.Contains('Customer Community')){
        	Consent__Share consentRec = new Consent__Share();   
            consentRec.UserOrGroupId =prescriberMap.get(Consent.Provider__c).OwnerId;
            consentRec.AccessLevel = 'Edit';
            consentRec.ParentId = Consent.ID;
            consentShare.add(consentRec);
            }
            
        } 
        if(!consentShare.isEmpty()) insert consentShare;
    }

}