OpafProjectVisualForcePages/force-app/main/default/objects/Consent__c/Consent__c.object-meta.xml
<CustomObject>
    <label>Consent</label>
    <nameField>
        <displayFormat>CON-{000000}</displayFormat>
        <label>Consent</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OpafProjectVisualForcePages/force-app/main/default/objects/Consent__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consent (Patient)</relationshipLabel>
    <relationshipName>Consent1</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Consent__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prescriber</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consent (Provider)</relationshipLabel>
    <relationshipName>Consent2</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Consent__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/classes/eConsentEmailTempalteController.cls
public class eConsentEmailTempalteController {
public string ConsentId{get;set;}
    public list<Consent__c> Consentlist = new  list<Consent__c>();
    public eConsentEmailTempalteController(){
        
    }
    public list<Consent__c> getConsentreclist(){
        Consentlist = [select id,Status__c,
                      Patient__c,
                      Patient__r.Firstname,
                      Patient__r.Lastname,
                      Patient__r.Email,
                      Patient__r.Name,
                      Patient__r.Phone,
                      Patient__r.fax,
                      Provider__r.name,
                      Provider__r.firstname,
                      Provider__r.Lastname,
                   	  Provider__r.Email,
                      Provider__r.Salutation,
                      Provider__r.Phone
                      
                    from Consent__c  where Id=:ConsentId ];
        if (Consentlist.size()>0){
        return Consentlist;
        }
        return null;
    }

}