OpafProjectVisualForcePages/force-app/main/default/objects/Consent__c/Consent__c.object-meta.xml
<CustomObject>
    <label>Consent</label>
    <nameField>
        <displayFormat>CON-{000000}</displayFormat>
        <label>Consent</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OpafProjectVfMods/force-app/main/default/objects/Consent__c/fields/Consent_Type__c.field-meta.xml
<CustomField>
    <fullName>Consent_Type__c</fullName>
    <label>Consent Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Consent</fullName>
            </value>
            <value>
                <fullName>Re-Enrollment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Consent__c/fields/DocusignCheck__c.field-meta.xml
<CustomField>
    <fullName>DocusignCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DocusignCheck</label>
    <type>Checkbox</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Consent__c/fields/EnvelopeId__c.field-meta.xml
<CustomField>
    <fullName>EnvelopeId__c</fullName>
    <label>EnvelopeId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Consent__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consent (Patient)</relationshipLabel>
    <relationshipName>Consent1</relationshipName>
    <type>Lookup</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Consent__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Consent__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paper Consent</fullName>
            </value>
            <value>
                <fullName>eConsent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Contact/fields/Legal_Rep__c.field-meta.xml
<CustomField>
    <fullName>Legal_Rep__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Legal Rep</label>
    <type>Checkbox</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Contact/fields/Legal_Rep_Condition_Check__c.field-meta.xml
<CustomField>
    <fullName>Legal_Rep_Condition_Check__c</fullName>
    <label>Legal Rep Condition Check</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>true</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Contact/fields/Legal_Rep_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Rep_First_Name__c</fullName>
    <label>Legal Rep First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Contact/fields/Legal_Rep_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Rep_Last_Name__c</fullName>
    <label>Legal Rep Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Contact/fields/Legal_Rep_Phone__c.field-meta.xml
<CustomField>
    <fullName>Legal_Rep_Phone__c</fullName>
    <label>Legal Rep Phone</label>
    <type>Phone</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Contact/fields/Legal_Rep_Rel_Other__c.field-meta.xml
<CustomField>
    <fullName>Legal_Rep_Rel_Other__c</fullName>
    <label>Legal Rep Rel Other</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Contact/fields/Legal_RepRelTypec__c.field-meta.xml
<CustomField>
    <fullName>Legal_RepRelTypec__c</fullName>
    <label>Legal Rep_Rel_Type__c</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Adult Child</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Adult Sibling</fullName>
            </value>
            <value>
                <fullName>Other (please specify)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
            </value>
            <value>
                <fullName>Presciber</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/classes/PatientConsentController.cls
public without sharing class PatientConsentController {
    
    @auraEnabled(cacheable=true)
    public Static contact getCurrentUserContact(){
        try {
            user userDetails = [select id,name,ContactId from user where Id =: userInfo.getUserId()];
            contact contactDetail = [select Id,FirstName,LastName,Email,Birthdate,
                                     Legal_Rep__c,Legal_Rep_First_Name__c,
                                     Legal_Rep_Last_Name__c,Legal_Rep_Phone__c,
                                     Legal_RepRelTypec__c,Legal_Rep_Condition_Check__c,Legal_Rep_Rel_Other__c,(select id,Type__c,DocusignCheck__c,Status__c from Consent1__r) from contact where Id =: userDetails.ContactId];
            return contactDetail;
        } catch (Exception ex) {
            throw new AurahandledException(ex.getMessage());
        }
    }
    
    @auraEnabled 
    public Static string updateConsent1(string ConsentId, string envelopeId){
        try {
            Consent__c con = new Consent__c();
            con.Id= consentId;
            con.Status__c = 'Received';
            con.DocusignCheck__c = true;
            con.EnvelopeId__c = envelopeId;
            String base64String = DS_OPAFController.getSignedDocument(envelopeId);
            ContentVersion cv = new ContentVersion();
            cv.Title = 'OnsiteConsentForm.pdf';
            cv.PathOnClient = 'OnsiteConsentForm.pdf';
            cv.VersionData = EncodingUtil.base64Decode(base64String);
            cv.Origin = 'H';
            cv.FirstPublishLocationId = consentId;
            cv.Document_Type__c = 'OnlineConsentForm';
        	insert cv;
            update con;
            return 'Success';
        } catch (Exception ex) {
            throw new AurahandledException(ex.getMessage());
        }
    }
    
    
    @auraEnabled 
    public Static string updateContact(Contact contactDetails, string consentType, List<Object> fileDatas){
        try {
            Contact newContact = new Contact(FirstName = contactDetails.FirstName,
                                             LastName = contactDetails.LastName,
                                             Email = contactDetails.Email,
                                             Birthdate = contactDetails.Birthdate,
                                             Legal_Rep_First_Name__c = contactDetails.Legal_Rep_First_Name__c,
                                             Legal_Rep_Last_Name__c = contactDetails.Legal_Rep_Last_Name__c,
                                             Legal_Rep_Phone__c = contactDetails.Legal_Rep_Phone__c,
                                             Legal_RepRelTypec__c = contactDetails.Legal_RepRelTypec__c,
                                             Legal_Rep_Rel_Other__c = contactDetails.Legal_Rep_Rel_Other__c,
                                             Id = contactDetails.Id);
            if(!string.isBlank(contactDetails.Legal_Rep_Condition_Check__c)){
                newContact.Legal_Rep__c = boolean.valueOf(contactDetails.Legal_Rep_Condition_Check__c);
                newContact.Legal_Rep_Condition_Check__c = string.valueof(contactDetails.Legal_Rep_Condition_Check__c);
            }
            Update newContact; 
            
            List<Consent__c> consentDetails = [select id,Type__c,Consent_Type__c,Patient__c from Consent__c where Patient__c =:newContact.Id];
            
            Consent__c newConsent = new Consent__c();
            newConsent.Patient__c = newContact.Id;
            newConsent.Type__c = consentType;
            
            if(!consentDetails.isEmpty()){
                newConsent.Id = consentDetails[0].Id; 
                newConsent.Consent_Type__c = 'Re-Enrollment';
            } else {
                newConsent.Consent_Type__c = 'New Consent';
            }
            
            upsert newConsent;
            
            if(consentType == 'Paper Consent' && !fileDatas.isEmpty()){
                List<ContentDocumentLink> cdl = DocumentUploadController.createContentVersion(fileDatas, newConsent.Id); 
                if (cdl == null) { return null; }
            }  
            
            return 'success';
        } catch (Exception ex) {
            throw new AurahandledException(ex.getMessage());
        }
    }
    
}