OpafProjectVfMods/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/Opaf_Care_Connect_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Opaf Care Connect Setting</label>
    <pluralLabel>Opaf Care Connect Settings</pluralLabel>
</CustomObject>

OpafProjectVfMods/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/Contact_Us__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us__c</fullName>
    <label>Contact Us</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/Footer_Content__c.field-meta.xml
<CustomField>
    <fullName>Footer_Content__c</fullName>
    <label>Footer Content</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/MG_Abilify_Maintena__c.field-meta.xml
<CustomField>
    <fullName>MG_Abilify_Maintena__c</fullName>
    <label>MG Abilify Maintena</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/MG_Jynarque__c.field-meta.xml
<CustomField>
    <fullName>MG_Jynarque__c</fullName>
    <label>MG Jynarque</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/MG_Rexulti__c.field-meta.xml
<CustomField>
    <fullName>MG_Rexulti__c</fullName>
    <label>MG Rexulti</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/MG_Samsca__c.field-meta.xml
<CustomField>
    <fullName>MG_Samsca__c</fullName>
    <label>MG Samsca</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/Month_Year__c.field-meta.xml
<CustomField>
    <fullName>Month_Year__c</fullName>
    <label>Month Year</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/Patient_Login_Header__c.field-meta.xml
<CustomField>
    <fullName>Patient_Login_Header__c</fullName>
    <label>Patient Login Header</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/Patient_Login_Text__c.field-meta.xml
<CustomField>
    <fullName>Patient_Login_Text__c</fullName>
    <label>Patient Login Text</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/Patient_Veeva_Code__c.field-meta.xml
<CustomField>
    <fullName>Patient_Veeva_Code__c</fullName>
    <label>Patient Veeva Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/PI_Abilify_Maintena__c.field-meta.xml
<CustomField>
    <fullName>PI_Abilify_Maintena__c</fullName>
    <label>PI Abilify Maintena</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/PI_Jynarque__c.field-meta.xml
<CustomField>
    <fullName>PI_Jynarque__c</fullName>
    <label>PI Jynarque</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/PI_Rexulti__c.field-meta.xml
<CustomField>
    <fullName>PI_Rexulti__c</fullName>
    <label>PI Rexulti</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/PI_Samsca__c.field-meta.xml
<CustomField>
    <fullName>PI_Samsca__c</fullName>
    <label>PI_Samsca</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/Prescriber_Login_Header__c.field-meta.xml
<CustomField>
    <fullName>Prescriber_Login_Header__c</fullName>
    <label>Prescriber Login Header</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/Prescriber_Login_Text__c.field-meta.xml
<CustomField>
    <fullName>Prescriber_Login_Text__c</fullName>
    <label>Prescriber Login Text</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/Prescriber_Veeva_Code__c.field-meta.xml
<CustomField>
    <fullName>Prescriber_Veeva_Code__c</fullName>
    <label>Prescriber Veeva Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/Privacy_Policy__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Policy__c</fullName>
    <label>Privacy Policy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/SAR_FDA_Email__c.field-meta.xml
<CustomField>
    <fullName>SAR_FDA_Email__c</fullName>
    <label>SAR_FDA_Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/SAR_FDA_Number__c.field-meta.xml
<CustomField>
    <fullName>SAR_FDA_Number__c</fullName>
    <label>SAR_FDA_Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/SAR_Otsuka__c.field-meta.xml
<CustomField>
    <fullName>SAR_Otsuka__c</fullName>
    <label>SAR_Otsuka</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVisualForcePages/force-app/main/default/objects/Opaf_Care_Connect_Setting__mdt/fields/Term_of_Use__c.field-meta.xml
<CustomField>
    <fullName>Term_of_Use__c</fullName>
    <label>Term of Use</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

OpafProjectVfMods/force-app/main/default/classes/LoginController.cls
global class LoginController {
 
@AuraEnabled
global static String checkPortal(String username, String password) {
 
try {
ApexPages.PageReference lgn =Site.login(username,password, '');
aura.redirect(lgn);
return null;
}
catch (Exception ex) {
return ex.getMessage();
}
}
 
@AuraEnabled
global static String forgotPassowrd(String username) {
String procesMsg = '';
 
if (Site.isValidUsername(username)) {
 
Site.forgotPassword(username);
procesMsg = 'Label.LoginResetSuccess';
}
else {
 
procesMsg = 'Label.LoginResetWarning';
}
 
return procesMsg;
 
}
    @AuraEnabled
    public static String getSelfRegistrationUrl() {
        Auth.AuthConfiguration authConfig = getAuthConfig();
        if (authConfig.getSelfRegistrationEnabled()) {
            return authConfig.getSelfRegistrationUrl();
        }
        return null;
    }
    @TestVisible
    private static Auth.AuthConfiguration getAuthConfig(){
        Id networkId = Network.getNetworkId();
        Auth.AuthConfiguration authConfig = new Auth.AuthConfiguration(networkId,'');
        return authConfig;
    }
    @AuraEnabled
    public static Boolean getIsSelfRegistrationEnabled() {
        Auth.AuthConfiguration authConfig = getAuthConfig();
        return authConfig.getSelfRegistrationEnabled();
    }
    @AuraEnabled
    public static String getForgotPasswordUrl() {
        Auth.AuthConfiguration authConfig = getAuthConfig();
        return authConfig.getForgotPasswordUrl();
    }
    @AuraEnabled(cacheable=true)
    public static Opaf_Care_Connect_Setting__mdt getCustomsettings(){
        
        Opaf_Care_Connect_Setting__mdt footer = [SELECT Contact_Us__c, Privacy_Policy__c, Term_of_Use__c, Footer_Content__c,
                                                    PI_Abilify_Maintena__c, PI_Jynarque__c, PI_Rexulti__c, PI_Samsca__c,
                                                    MG_Abilify_Maintena__c, MG_Jynarque__c, MG_Rexulti__c, MG_Samsca__c,
                                                    SAR_Otsuka__c, SAR_FDA_Number__c, SAR_FDA_Email__c,Prescriber_Veeva_Code__c,Patient_Veeva_Code__c,Month_Year__c,Prescriber_Login_Header__c,Prescriber_Login_Text__c,Patient_Login_Header__c,Patient_Login_Text__c
                                                    FROM Opaf_Care_Connect_Setting__mdt
                                                    WHERE MasterLabel = 'Footer Settings'];
        return footer;
    }
}